# This sample YAML file shows how to configure an Azure Pipeline to analyze a repository using the CodeQL CLI Bundle
# When a repository is stored in GitHub
# To run Codeql in azure repos see: https://learn.microsoft.com/en-us/azure/devops/repos/security/github-advanced-security-code-scanning?view=azure-devops
# This example assumes a Linux environment

# The pipeline needs have a variable called GITHUB_TOKEN (don't forget to set it as secret)
# This secret will contain a personal access token. Either classic or fine grained (preferably)
# The Clasic token requires the following scopes: Repo
# The fine grained token requires the following permissions: Code scanning alerts (read and write)

# Adapt the trigger to your needs
trigger:
    branches:
      include:
      - '*'
    paths:
      exclude:
      - test/*
      - doc/*
      - lib/*
      include:
      - src/*

variables:
  # Language to scan. Possible values
  #   cpp, csharp, go, java, javascript, python, ruby, swift
  language: javascript   

stages:
- stage:
  jobs:
    - job:
      displayName: CodeQL analyze

      pool:
        vmImage: 'ubuntu-latest'
      workspace:
          clean: all
      steps:

        # OPTIONAL: Download CodeQL CLI Bundle
        # The CodeQL bundle (containing the CodeQL CLI as well as the pre-compiled CodeQL Query Suites, which is recommended for CI/CD integration) can either be download as part of the pipeline,
        # or pre-downloaded and placed on the CI/CD build machine(s). In this example, we download the latest CLI bundle (at time of writing) as part of the pipeline from
        # https://github.com/github/codeql-action/releases, extract it and place it on the PATH.
        - script: |          
              wget https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-linux64.tar.gz \
                -O ../codeql-bundle-linux64.tar.gz \
                --show-progress \
                --progress=dot:mega 

              tar xzvf ../codeql-bundle-linux64.tar.gz -C ../
              rm ../codeql-bundle-linux64.tar.gz

              # Make sure CLI is on the path
              cli_path="$(cd ..; pwd)/codeql"
              echo "##vso[task.prependpath]$cli_path"

              sarif_file=$(mktemp)

              echo "##vso[task.setvariable variable=sarif_file;]$sarif_file"
          displayName: Download CodeQL CLI Bundle

        # Create CodeQL Database
        # Create a CodeQL database for a source tree that can be analyzed using one of the CodeQL products.
        # Note that if the --command flag is omitted for compiled languages, the AutoBuilder will be used. For complex build instructions, consider placing build commands inside a script
        # and pass that to --command, or use indirect build tracing (aka. "sandwich mode").
        # Full documentation for database create step: https://codeql.github.com/docs/codeql-cli/manual/database-create/
        - script: |
            codeql database create db \
              --language=$(language) \
              --github-url=https://github.com/

          displayName: Create CodeQL Database

        # Analyze CodeQL Database
        # Analyze a CodeQL database, producing meaningful results in the context of the source code.
        # Run a query suite (or some individual queries) against a CodeQL database, producing results, styled as alerts or paths, in SARIF or another interpreted format.
        # Note that the suite argument can accept one of the pre-compiled, out-of-the-box query suites: code-scanning, security-extended, or security-and-quality
        # Full documentation for database analyze step: https://codeql.github.com/docs/codeql-cli/manual/database-analyze/
        - script: |
            codeql database analyze \
              --format=sarif-latest \
              --sarif-category="$(language)" \
              --sarif-add-baseline-file-info \
              --output="$(sarif_file)" \
              db $(language)-security-and-quality.qls
          displayName: Analyze CodeQL Database
            
        # Upload results to GitHub
        # Uploads a SARIF file to GitHub code scanning.
        # For context, please see https://docs.github.com/en/rest/reference/code-scanning#upload-an-analysis-as-sarif-data
        # A GitHub Apps token or personal access token must be set. For best security practices, it is recommended to set the --github-auth-stdin flag and pass the token to the command through standard input. Alternatively, the GITHUB_TOKEN environment variable can be set.
        # This token must have the security\_events scope.
        # Documentation for creating GitHub Apps or Personal Access Tokens are available here: https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token
        # Full documentation for github upload-results step: https://codeql.github.com/docs/codeql-cli/manual/github-upload-results/
        - script: |
            echo ""
            codeql github upload-results \
              --sarif="$(sarif_file)" \
              --github-url=https://github.com/ \
              --repository="$(Build.Repository.Name)" \
              --ref="$(Build.SourceBranch)" \
              --commit="$(Build.SourceVersion)"
          displayName: Upload results to GitHub $(Build.Repository.Name)
          env:
            GITHUB_TOKEN: $(GITHUB_TOKEN)

